### ISSUE TITLE
ERROR NetworkEventFiringHandler exception  java.lang.RuntimeException: Missing

### ISSUE THREAD

**Issue by IAmNotGEM** [AE2-UEL/Applied-Energistics-2#414]
29.03 06:06:39 [服务器] ERROR NetworkEventFiringHandler exception
29.03 06:06:39 [服务器] 信息 java.lang.RuntimeException: Missing
29.03 06:06:39 [服务器] 信息 at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:311) ~[FMLServerHandler.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:548) ~[FMLCommonHandler.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$10.selectNetworks(FMLOutboundHandler.java:324) ~[FMLOutboundHandler$OutboundTarget$10.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:373) ~[FMLOutboundHandler.class:?]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
29.03 06:06:39 [服务器] 信息 at net.minecraftforge.fml.common.network.FMLEventChannel.sendToServer(FMLEventChannel.java:224) ~[FMLEventChannel.class:?]
29.03 06:06:39 [服务器] 信息 at appeng.core.sync.network.NetworkHandler.sendToServer(NetworkHandler.java:124) ~[NetworkHandler.class:?]
29.03 06:06:39 [服务器] 信息 at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:189) ~[PacketInventoryAction.class:?]
29.03 06:06:39 [服务器] 信息 at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:50) ~[AppEngServerPacketHandler$1.class:?]
29.03 06:06:39 [服务器] 信息 at appeng.core.sync.AppEngPacket.processPacket(AppEngPacket.java:108) ~[AppEngPacket.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
29.03 06:06:39 [服务器] 信息 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
29.03 06:06:39 [服务器] 信息 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
29.03 06:06:39 [服务器] 信息 at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840) [MinecraftServer.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) [MinecraftServer.class:?]
29.03 06:06:39 [服务器] 信息 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
29.03 06:06:39 [服务器] 信息 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
29.03 06:06:39 [服务器] WARN More than one exception was raised. Will report only the first one and log others.

**Comment by NotMyWing** [comment]
Could you please provide more info what you did to cause this? What kind of server software are you running?

**Comment by IAmNotGEM** [comment]
> Could you please provide more info what you did to cause this? What kind of server software are you running?

Mohist 1.12.2
