### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by zz314657917** [AE2-UEL/Applied-Energistics-2#474]
Time: 7/10/24 4:55 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:557)
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:128)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:40)
	at appeng.me.Grid.update(Grid.java:229)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:196)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_893_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:884)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
	at java.lang.Thread.run(Thread.java:750)

No Mixin Metadata is found in the Stacktrace.
[Uploading crash-2024-07-10_16.55.35-server.txt…]()

**Comment by zeng-github01** [comment]
@zz314657917 Is there something wrong with your Crafting CPU, or is it not AE2's own CPU unit?

**Comment by zz314657917** [comment]
Extra CPUs
Lazy AE2
Do I have these two modules above, and they are not compatible?

**Comment by zeng-github01** [comment]
> Extra CPUs Lazy AE2 Do I have these two modules above, and they are not compatible?

I have used these two mods and there is no problem. There is no good way. And the log you uploaded is wrong and cannot be downloaded.

**Comment by NotMyWing** [comment]
Hello! The crafting grid should optimally never contain invalid clusters. When you say "consistently", do you mean you have a consistent reproduction scenario? Also, please upload the log file correctly.

**Comment by zz314657917** [comment]
[crash-2024-07-16_00.55.00-server.txt](https://github.com/user-attachments/files/16244006/crash-2024-07-16_00.55.00-server.txt)
Look at this crash report以上翻译结果来自有道神经网络翻译（YNMT）· 通用场景

**Comment by zeng-github01** [comment]
> [crash-2024-07-16_00.55.00-server.txt](https://github.com/user-attachments/files/16244006/crash-2024-07-16_00.55.00-server.txt)
> Look at this crash report
> 

估计是你使用的服务器造成的干扰
